### ISSUE TITLE
Add a error catch for the time difference between forked repo is available and that it can be checked out. 

### ISSUE THREAD

**Issue by muratmaga** [pieper/SlicerMorphoDepot#7]
Testing with this repo:

https://github.com/amm554/MD_Mus_musculus/

When I double click on my assigned issue in SlicerMorphoDepot, this error is generated:
```
exouser@instance-55:/$ vglrun -d egl ~/Slicer/Slicer 
libpng warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space
libpng warning: iCCP: known incorrect sRGB profile
Switch to module:  "Welcome"
Switch to module:  "MorphoDepot"
('[{"number":1,"repository":{"name":"MD_Mus_musculus","nameWithOwner":"amm554/MD_Mus_musculus"},"title":"segment skull"},{"number":7,"repository":{"name":"MD_E15","nameWithOwner":"pieper/MD_E15"},"title":"Test MorphoDepot prototype"},{"number":46,"repository":{"name":"MorphoCloudWorkflow","nameWithOwner":"MorphoCloud/MorphoCloudWorkflow"},"title":"Screen resolution limitation in xfce4 "},{"number":45,"repository":{"name":"MorphoCloudWorkflow","nameWithOwner":"MorphoCloud/MorphoCloudWorkflow"},"title":"Missing packages to support R/devtools"},{"number":44,"repository":{"name":"MorphoCloudWorkflow","nameWithOwner":"MorphoCloud/MorphoCloudWorkflow"},"title":"Better openGl performance in CPU nodes"},{"number":31,"repository":{"name":"Morphology-analysis","nameWithOwner":"hdr-bgnn/Morphology-analysis"},"title":"color legend"}]\n', None)
('[{"name":"MD_E15"},{"name":"MorphoCloudWorkflow"},{"name":"fake_tutorial"},{"name":"MorphoCloudPortal"},{"name":"SlicerMorphR"},{"name":"Slicer"},{"name":"exosphere"},{"name":"pyRserve"},{"name":"nnmouse"},{"name":"scanner_stuff"},{"name":"mouse_CT_atlas"},{"name":"SlicerMorph_Rexamples"},{"name":"MONAILabel"},{"name":"Tutorials"},{"name":"demo"},{"name":"scanner_logs"},{"name":"dummy"},{"name":"ProjectWeek"},{"name":"fatih"},{"name":"rtd-tutorial"},{"name":"SlicerMorph"},{"name":"terms"},{"name":"blog"},{"name":"Scripts"},{"name":"test_images"},{"name":"bgnn_related"},{"name":"MMLLM"},{"name":"monai-deepedit"},{"name":"VolImportModule"},{"name":"SampleData"}]\n', None)
('', None)
("Cloning into '/home/exouser/Documents/MD_Mus_musculus'...\nremote: Repository not found.\nfatal: repository 'https://github.com/muratmaga/MD_Mus_musculus.git/' not found\nfailed to run git: exit status 128\n", None)
Traceback (most recent call last):
  File "/media/volume/MyData/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 209, in onItemDoubleClicked
    self.logic.loadIssue(issue, repoDirectory)
  File "/media/volume/MyData/SlicerMorphoDepot/MorphoDepot/MorphoDepot.py", line 273, in loadIssue
    self.localRepo = git.Repo(localDirectory)
  File "/home/exouser/Slicer/lib/Python/lib/python3.9/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/exouser/Documents/MD_Mus_musculus
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1752, resource id: 14691971, major code: 40 (TranslateCoords), minor code: 0
```

It appears if made the fork my participant account (muratmaga), but not sure why it is generating the repository not found error?

**Comment by muratmaga** [comment]
OK, there must be a timing issue. because second time I tried it downloaded the volume. So perhaps we need to add some delay? Or an error catch (that it tries until the forked repo becomes available).

**Comment by muratmaga** [comment]
It all worked well (that is up to PR submission). I think the basics are sorted out. Doing without branch protection and not adding people as collaborators are going to simplify things...

**Comment by pieper** [comment]
It'll be hard to debug a timing issue, but I added a check that if this fails a dialog box will suggest retrying in a few seconds.
